#!/bin/sh

echo "`date`" > /tmp/nmbd.log
echo "starting smbd nmbd" >> /tmp/nmbd.log

if [ -n "`pidof smbd`" ] ; then
    echo "Stopping smbd:"
    killall smbd
fi

if [ -n "`pidof nmbd`" ] ; then
    echo "Stopping nmbd:"
    killall nmbd
fi

#sleep 2

echo "Starting smbd:"
/opt/sbin/smbd -D;
echo "smbd rc: $?" >> /tmp/nmbd.log
echo "Starting nmbd:"
/opt/sbin/nmbd -D;
echo "nmbd rc: $?" >> /tmp/nmbd.log
